#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J bwa
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load bwa/0.7.17
module load samtools

#bwa commands

#create bwa index
bwa index /home/tgiffin/genome_analyses/03_DNA_assembly/DNA_assembly_results/final.contigs.fa

#bwa mem
bwa mem /home/tgiffin/genome_analyses/03_DNA_assembly/DNA_assembly_results/final.contigs.fa \
-t 2 \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz |\
samtools view -S -b - |\
samtools sort -o - > bwa_results_SRR4342129.bam

bwa mem /home/tgiffin/genome_analyses/03_DNA_assembly/DNA_assembly_results/final.contigs.fa \
-t 2 \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342133_1.paired.trimmed.fastq.gz \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342133_2.paired.trimmed.fastq.gz |\
samtools view -S -b - |\
samtools sort -o - > bwa_results_SRR4342133.bam
