#!/bin/bash -l


#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 15:00:00
#SBATCH -J bwa
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load bwa/0.7.17
module load samtools

#concatenate bins
for i in {1..49};

do

bwa index /home/tgiffin/genome_analyses/09_annotation/${i}_prokka_results/annotation.fna

#run paired -end DNA sample 1 against bins
bwa mem -t 4 /home/tgiffin/genome_analyses/09_annotation/${i}_prokka_results/annotation.fna \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz \
/home/tgiffin/genome_analyses/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz |\
samtools sort -o ${i}_SRR4342129_DNA_alignment.bam

samtools index ${i}_SRR4342129_DNA_alignment.bam ${i}_SRR4342129_DNA_alignment.bam.bai

samtools idxstats ${i}_SRR4342129_DNA_alignment.bam > ${i}_SRR4342129_idxstats.txt

awk '{sum+=$3}END{print sum}' ${i}_SRR4342129_idxstats.txt > ${i}_SRR4342129_mapped_reads.txt

samtools flagstat ${i}_SRR4342129_DNA_alignment.bam > ${i}_SRR4342129.flagstat

rm ${i}_SRR4342129_DNA_alignment.bam

done
