#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:20:00
#SBATCH -J fastqc_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load FastQC/0.11.9

#commands
fastqc /home/tgiffin/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz \
/home/tgiffin/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz \
/home/tgiffin/DNA_trimmed/SRR4342133_1.paired.trimmed.fastq.gz \
/home/tgiffin/DNA_trimmed/SRR4342133_2.paired.trimmed.fastq.gz \
-o fastqc_DNA_results
