#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:20:00
#SBATCH -J fastqc_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load FastQC/0.11.9

#commands
fastqc /home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/forward_paired_SRR4342137.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/forward_paired_SRR4342139.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/forward_unpaired_SRR4342137.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/forward_unpaired.SRR4342139.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/reverse_paired_SRR4342137.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/reverse_paired_SRR4342139.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/reverse_unpaired_SRR4342137.fastq.gz \
/home/tgiffin/genome_analyses/02_RNA_trimming/trimmed_RNA/reverse_unpaired_SRR4342139.fastq.gz \
-o /home/tgiffin/genome_analyses/01_reads_quality_control/fastqc_RNA_post_trim_results
