#!/bin/bash -l


#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J metabat
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load MetaBat/2.12.1

#metabat commands
jgi_summarize_bam_contig_depths --outputDepth depth.txt /home/tgiffin/genome_analyses/05_alignment/*.bam

metabat2 -i /home/tgiffin/genome_analyses/03_DNA_assembly/DNA_assembly_results/final.contigs.fa \
 -a depth.txt -o bins
