#!/bin/bash -l


#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 01:00:00
#SBATCH -J quast
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load quast/5.0.2

#quast commands
metaquast.py /home/tgiffin/genome_analyses/03_DNA_assembly/DNA_assembly_results/final.contigs.fa
