#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:20:00
#SBATCH -J trimmomatic
#SBATCH --mail-type=ALL
#SBATCH --mail-user victoria-marie.giffin.2741@student.uu.se

#load modules
module load bioinfo-tools
module load trimmomatic/0.39

#trim commands
trimmomatic PE /home/tgiffin/RNA_untrimmed/SRR4342137.1.fastq.gz \
/home/tgiffin/RNA_untrimmed/SRR4342137.2.fastq.gz \
forward_paired_SRR4342137.fastq.gz \
forward_unpaired_SRR4342137.fastq.gz \
reverse_paired_SRR4342137.fastq.gz \
reverse_unpaired_SRR4342137.fastq.gz \
ILLUMINACLIP:/home/tgiffin/genome_analyses/02_RNA_trimming/adapter_sequences:2:30:10 \
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50

trimmomatic PE /home/tgiffin/RNA_untrimmed/SRR4342139.1.fastq.gz \
/home/tgiffin/RNA_untrimmed/SRR4342139.2.fastq.gz \
forward_paired_SRR4342139.fastq.gz \
forward_unpaired.SRR4342139.fastq.gz \
reverse_paired_SRR4342139.fastq.gz \
reverse_unpaired_SRR4342139.fastq.gz \
ILLUMINACLIP:/home/tgiffin/genome_analyses/02_RNA_trimming/adapter_sequences:2:30:10 \
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50
